### ISSUE TITLE
 All of the bugs are not reproduced (i.e., the reproduced column is False)

### ISSUE THREAD

**Issue by Espresso-Kp** [sieve-project/sieve#119]
Hi! I tried to reproduce the full evaluation of paper, but I got 'False' results for all bugs in ‘reproduced’ column. I checked the test results file and the "exception_message" is like this:

"exception_message": "Traceback (most recent call last):\n  File \"/home/sieve/.local/lib/python3.8/site-packages/docker/api/client.py\", line 214, in _retrieve_server_version\n    return self.version(api_version=False)[\"ApiVersion\"]\n  File \"/home/sieve/.local/lib/python3.8/site-packages/docker/api/daemon.py\", line 181, in version\n    return self._result(self._get(url), json=True)\n  File \"/home/sieve/.local/lib/python3.8/site-packages/docker/utils/decorators.py\", line 46, in inner\n    return f(self, *args, **kwargs)\n  File \"/home/sieve/.local/lib/python3.8/site-packages/docker/api/client.py\", line 237, in _get\n    return self.get(url, **self._set_request_timeout(kwargs))\n  File \"/home/sieve/.local/lib/python3.8/site-packages/requests/sessions.py\", line 600, in get\n    return self.request(\"GET\", url, **kwargs)\n  File \"/home/sieve/.local/lib/python3.8/site-packages/requests/sessions.py\", line 587, in request\n    resp = self.send(prep, **send_kwargs)\n  File \"/home/sieve/.local/lib/python3.8/site-packages/requests/sessions.py\", line 701, in send\n    r = adapter.send(request, **kwargs)\n  File \"/home/sieve/.local/lib/python3.8/site-packages/requests/adapters.py\", line 486, in send\n    resp = conn.urlopen(\n  File \"/home/sieve/.local/lib/python3.8/site-packages/urllib3/connectionpool.py\", line 790, in urlopen\n    response = self._make_request(\n  File \"/home/sieve/.local/lib/python3.8/site-packages/urllib3/connectionpool.py\", line 496, in _make_request\n    conn.request(\nTypeError: request() got an unexpected keyword argument 'chunked'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"sieve.py\", line 557, in run_test\n    setup_cluster(test_context)\n  File \"sieve.py\", line 307, in setup_cluster\n    redirect_kubectl()\n  File \"sieve.py\", line 161, in redirect_kubectl\n    client = docker.from_env()\n  File \"/home/sieve/.local/lib/python3.8/site-packages/docker/client.py\", line 96, in from_env\n    return cl

Do you have any idea why this happened? I don't understand what does "request() got an unexpected keyword argument 'chunked'" means and it seems not because kind cluster accidentally crashes as you mentioned in README.md.

Thanks in advance for any help!

**Comment by marshtompsxd** [comment]
Sorry for the late response. It seems that sieve is not able to connect to docker in the `redirect_kubectl` function. Could you check whether the docker containers are running well in your local setup?

**Comment by marshtompsxd** [comment]
`redirect_kubectl` is only called for stale-state testing. You can also try other testing patterns before resolving this failure. Such as `python3 reproduce_bugs.py -c rabbitmq-operator -b intermediate-state-1`

**Comment by Espresso-Kp** [comment]
Hi, thank you for the reply. I have run this command "python3 reproduce_bugs.py -p rabbitmq-operator -b intermediate-state-1" but it gave me similar error information as below:

TypeError: request() got an unexpected keyword argument 'chunked'
docker.errors.DockerException: Error while fetching server API version: request() got an unexpected keyword argument 'chunked'

Indeed it looks like something wrong with docker, but I passed the "check_env.py" except mage not detected. Is there other way to check if the docker containers are running properly in my local setup?

**Comment by marshtompsxd** [comment]
I am not sure why you encounter this error. I see some people encounter similar problems when using docker and this might help: https://stackoverflow.com/questions/64952238/docker-errors-dockerexception-error-while-fetching-server-api-version

`check_env.py` only checks if docker is installed, but does not check if docker is running (correctly).

**Comment by Espresso-Kp** [comment]
Although I don't really understand the root cause of this issue, it was solved by downgrading the requests version. It is likely because there is a conflict issue between urllib3 and requests 2.30.0 (which I used). 

pip uninstall requests
pip install requests==2.28.1

**Comment by marshtompsxd** [comment]
Thanks for letting us know the solution here. We will document this issue to help other users.
