### ISSUE TITLE
Error while creating cluster with ghcr.io/sieve-project/action/node:v1.18.9-test image

### ISSUE THREAD

**Issue by yashdeep97** [sieve-project/sieve#127]
Thanks for documenting the process to run sieve to reproduce the stale-state bug on the RabbitMQ operator.

I've been following the steps and while running the command
`python3 sieve.py -c rabbitmq-operator -m test -w recreate -p bug_reproduction_test_plans/rabbitmq-operator-stale-state-1.yaml`

I am facing and issue while creating the Kubernetes cluster with the ghcr.io/sieve-project/action/node:v1.18.9-test image.
I am getting the following error:

```
ERROR: failed to create cluster: failed to init node with kubeadm: command "docker exec --privileged kind-control-plane kubeadm init --skip-phases=preflight --config=/kind/kubeadm.conf --skip-token-print --v=6" failed with error: exit status 1
```

And successive attempts failing to connect to kind-external-load-balancer
```[wait-control-plane] Waiting for the kubelet to boot up the control plane as static Pods from directory "/etc/kubernetes/manifests". This can take up to 4m0s
I0928 21:37:50.729870     139 round_trippers.go:443] GET https://kind-external-load-balancer:6443/healthz?timeout=10s  in 1 milliseconds
I0928 21:37:50.730110     139 request.go:907] Got a Retry-After 1s response for attempt 1 to https://kind-external-load-balancer:6443/healthz?timeout=10s
I0928 21:37:51.731382     139 round_trippers.go:443] GET https://kind-external-load-balancer:6443/healthz?timeout=10s  in 1 milliseconds
I0928 21:37:51.731424     139 request.go:907] Got a Retry-After 1s response for attempt 2 to https://kind-external-load-balancer:6443/healthz?timeout=10s
I0928 21:37:52.732674     139 round_trippers.go:443] GET https://kind-external-load-balancer:6443/healthz?timeout=10s  in 1 milliseconds
```

Would really appreciate any help regarding this issue.  (I am running kind on Ubuntu x86_64)

**Comment by marshtompsxd** [comment]
Hi @yashdeep97 Sorry for the late response.

The error `ERROR: failed to create cluster: failed to init node with kubeadm` sometimes might happen when running an old kind image with a newer version of kind (v1.18.9 is a quite old version these days). You can try the newer kind version like v1.24.10 (in our repo). You can also build other versions of kind image using the build `build.py` script.

**Comment by yashdeep97** [comment]
Thanks for your response! I will close this issue.
