### ISSUE TITLE
Add more information about required platform to run Sieve

### ISSUE THREAD

**Issue by embano1** [sieve-project/sieve#6]
The README only states that `kind` is required but it would be good to explicitly state that:

- Kubernetes (incl. min_version) is currently required to use/run Sieve
- `etcd` as the backing store is assumed

The second bullet is important IMHO as per my understanding we rely on the monotonicity and total ordering guarantees of `etcd` (revisions/resourceVersions) for the correctness of the checker. K8s (and derivatives like k3s) allow for custom `stores` (backends) which might have different semantics or not provide linearizability guarantees.

Please correct me if my understanding of the required behavior of the underlying K8s `store` to reliably detect bugs with Sieve is correct. If not, bullet two might be obsolete.

**Comment by embano1** [comment]
I'd have to double-check but IIRC k3s uses sqllite and AKS (Azure) uses CosmosDB (please keep me honest here). Since the K8s API conventions state that RV is supposed to be treated an opaque value, relying and generalizing on monotonicity might not always hold. Though to be fair, I assume k3s and AKS actually use the same monotonic counter semantics (with different backend implementations).

**Comment by lalithsuresh** [comment]
Cool! For now, my understanding is that we don't rely on resource versions but we do rely on the store providing linearizability semantics to define what a history is (@marshtompsxd please correct me if I'm wrong).

**Comment by tianyin** [comment]
This is a great point @embano1!  

> k3s uses sqllite

I think sqllite is not too different from `etcd` as the history can easily be defined.

> AKS (Azure) uses CosmosDB
> we do rely on the store providing linearizability semantics to define what a history

It's interesting if the datastore is *not* strongly consistent. I see CosmosDB provides different levels of consistency. 

@embano1 is AKZ using those weak-consistency configurations?

**Comment by marshtompsxd** [comment]
> Cool! For now, my understanding is that we don't rely on resource versions but we do rely on the store providing linearizability semantics to define what a history is (@marshtompsxd please correct me if I'm wrong).

Yes. And the bug patterns should still exist when the underlying datastore is not strongly consistent.

**Comment by embano1** [comment]
Thx for the clarification, closing this issue then.

> is AKZ using those weak-consistency configurations?

Can't tell (have no insights), but I'd assume for AKS they'd use strongly consistent backend configurations since this assumption is built into K8s design.
