### ISSUE TITLE
Events related to services are not detected from API server side

### ISSUE THREAD

**Issue by laphets** [sieve-project/sieve#7]
As mentioned in previous meeting, through batch analysis on mongodb operator, there are some cases that have matched for crucial event, but not detect side effect event on API server side (however, we observed side effect issued by the operator).
And all of those failed patterns have the crucial event of `service`, e.g.
```yaml
se-name: mongodb-cluster-cfg
se-namespace: default
se-rtype: service
se-etype: ADDED
```

After dumping all the event keys from [here](https://github.com/sieve-project/sieve/blob/main/sonar-client/time-travel-client.go#L28), I observed that keys related to `service` is like `/services/specs/default/mongodb-cluster-cfg` or `/services/endpoints/default/mongodb-cluster-cfg`, and the event resource is parsed as `spec` / `endpoints` instead of `service` according to logic [here](https://github.com/sieve-project/sieve/blob/main/sonar-client/time-travel-client.go#L33). 

After looking into [some source code](https://github.com/kubernetes/kubernetes/blob/a5b117fab4ec58cbbbf8a013367edf359f4d682f/pkg/kubeapiserver/default_storage_factory_builder.go#L40) of k8s, I figure the reason behind this. The basic idea is that k8s will add some special prefix to certain resources as the key stored in etcd. For `endpoints`, the key is then transformed into `services/endpoints`, for `service`, the key is `services/specs`. As for our matching, we also need to consider for those special prefix.

The current fix is to manually map the `services/endpoints` to `endpoints`, and `services/specs` to `services`. After the fix, `service` related side effect event can be successfully detected and sieve can then detect bug related to `service` ADD / DELETE.

**Comment by marshtompsxd** [comment]
Nice catch!

> The basic idea is that k8s will add some special prefix to certain resources as the key stored in etcd. For endpoints, the key is then transformed into services/endpoints, for service, the key is services/specs. As for our matching, we also need to consider for those special prefix.

Yes, the different naming (and even different data structures) for the same resource object at different components is tricky. We might need some rules to associate such events.

**Comment by tianyin** [comment]
close; if my understanding is correct, we don't find new bugs but it helps match the events in the learning stage to make sure we don't miss later.
