### ISSUE TITLE
What creates mask.json?

### ISSUE THREAD

**Issue by robbie-demuth** [sieve-project/sieve#84]
I've been trying to port a controller to test it using Sieve. I've stumbled across a variety of minor issues, but have thus far managed to overcome them, so I won't talk about them here. Now, however, I'm at an issue that I'm not sure how to resolve. I've been following https://github.com/sieve-project/sieve/blob/main/docs/port.md and am currently at

> First run Sieve learning stage
> ```
> python3 sieve.py -p your-controller -t your-test-case-name -s learn -m learn-twice
> ```

Sieve appears to properly deploy my controller and execute my test case. Once the test case finishes executing, however, Sieve fails because it cannot find a `mask.json` file:

```
wait for final grace period 50 seconds
Generating controller family list...
Generating state update summary...
Generating end state...
Sanity checking the sieve log log/appian-operator/recreate/learn/learn-once/learn.yaml/sieve-server.log...
[FAIL] cannot find mask.json
```

The error appears to be stemming from [here](https://github.com/sieve-project/sieve/blob/main/sieve_analyzer/analyze.py#L386). What creates this file? Is it possible that an earlier step created it but I've since deleted it? Is the file meant to be created manually? I see no reference to it in the docs and it appears that the file isn't manually created based on its appearance in other examples.

Thanks!

PS: I would share the code, but the operator I'm porting is (currently) closed source. Please let me know what information might be useful and I'll try to share if I can!

**Comment by marshtompsxd** [comment]
Hi @robbie-demuth , thank you for your interest in Sieve! 

For the mask.json issue, could you check whether Sieve continues running after reporting this error and generates a mask.json in `examples/your-controller-name/oracle/your-test-name`? `learn-twice` means Sieve is going to run the same test workload twice and it generates the mask.json only in its second run. Typically the error only happens in the first run and is benign. You can ignore the error if Sieve generates the mask.json at the end of the second run. The error is indeed misleading and I will fix it. Please let me know if you still cannot find mask.json at the end of `learn-twice` run.

**Comment by robbie-demuth** [comment]
Hey, @marshtompsxd 👋 thanks for the quick response! I'll give that a shot today. When I saw the "failure" and saw Sieve delete and recreate the kind cluster, I figured it was just straight up retrying. Given how long it takes to run the tests on my machine and how resource intensive they are, I stopped Sieve instead of letting it continue. I'll report back on how things go 👍

**Comment by robbie-demuth** [comment]
It took a while, but I was finally able to run

```bash
python3 sieve.py -p your-controller -t your-test-case-name -s learn -m learn-twice
```

I'm now on to trying to run the test plans and had a few comments / questions:

1.

> Sieve will generate the test plans for intermediate-states, unobserved-states and stale-stateing testing patterns in `log/your-controller/your-test-case-name/learn/learn-twice/{intermediate-state, unobserved-states, stale-state}`

The test plans are actually generated in `log/your-controller/your-test-case-name/learn/learn-twice/learn.yaml/{intermediate-state, unobserved-states, stale-state}` (note the `learn.yaml`)

> If you want to run one of the test plans:
>
> ```bash
> python3 sieve.py -p your-controller -t your-test-case-name -s test -m intermediate-state -c path-to-the-test-plan
> ```

2.

I don't think `-m intermediate-state` is valid. Running the above command resulted in

```
Usage: python3 sieve.py [options]

sieve.py: error: invalid test mode option: intermediate-state
```

From [the code](https://github.com/sieve-project/sieve/blob/main/sieve.py#L737-L743), it looks like `-m` should be set to `test`

```python
    parser.add_option(
        "-m",
        "--mode",
        dest="mode",
        help="MODE: vanilla, test, learn-once, learn-twice",
        metavar="MODE",
    )
```

3. Sieve generated hundreds of test plans (which I suppose is a good thing). Where do I go from here? Should I run all of them to test for bugs? Given how long it takes my test case to execute, I don't know if this is practical

Thanks for the assistance!

**Comment by marshtompsxd** [comment]
Hi @robbie-demuth , thanks for your valuable feedback!

Regarding 1 and 2, I am sorry that the documentation is not updated, and thank you for finding the bugs in the documentation! I will update the documentation this week.

Regarding 3, yes generating many test plans is a good sign. Usually, you can start by running all the test plans. Sieve supports running all the test plans in one batch by 
```
python3 sieve.py -p your-controller -t your-test-case-name -s test -c the-folder-contains-your-test-plans --batch 
```
All the test results will appear in `sieve_test_results` folder as json files. I just pushed a script for selecting the test results that might indicate a bug and you can run it by `python3 report_bugs.py` (please pull). You can refer to the test results pointed to by this script. Each test result file should have sufficient information for debugging including the full path to the test plan and the detected inconsistencies. You can also rerun a particular test plan to reproduce a bug by
```
python3 sieve.py -p your-controller -t your-test-case-name -s test -c your-test-plan
```

**Comment by marshtompsxd** [comment]
> Given how long it takes my test case to execute, I don't know if this is practical

This indeed could be a concern when you have many test plans. The estimated testing time is (number of test plans) * (time of running the test case once). We prepared a script `test_script/runtest.sh` to parallelize test runs on multiple machines. If you have more than one machine to run the tests you can consider the following
```
cd test_script
bash runtest.sh your-controller-name
```
All the test results will be gathered in a `test_script/test-summary-xxx.json`. Note that the script was for our internal testing and there could be some usability issues. It assumes the following:
1. you have a `hosts` file including all the machines to run the tests like the following (the first `:` means the local host)
```
:
vm2
vm3
```
2. you have a `remotehosts` that is the same as `hosts` except that there is no local host
```
vm2
vm3
```
3. All the machines have `sieve` downloaded at `/home/ubuntu/sieve` -- you can for sure modify this file path in `runtest.sh`
4. All the machines should be configured with the proper environment to run Sieve. You can consider using our ansible scripts in `deploy_script` to configure your machine, but note that these scripts will install some software like docker and kind.

**Comment by marshtompsxd** [comment]
Thank you for using Sieve to test your controller again! And I apologize for all the usability issues you have encountered. I will update the documentation and also include the steps to run and diagnose tests this week.

**Comment by marshtompsxd** [comment]
I also noticed that there seem to be some interesting warnings like
```
"State-update summaries inconsistency: statefulset/default/appian-k8s-service-manager-analytics00 DELETED inconsistency: 1 event(s) seen during reference run, but 0 seen during testing run",
"State-update summaries inconsistency: statefulset/default/appian-k8s-service-manager-analytics01 DELETED inconsistency: 1 event(s) seen during reference run, but 0 seen during testing run",
"State-update summaries inconsistency: statefulset/default/appian-k8s-service-manager-analytics02 DELETED inconsistency: 1 event(s) seen during reference run, but 0 seen during testing run",
"State-update summaries inconsistency: statefulset/default/appian-k8s-service-manager-content DELETED inconsistency: 1 event(s) seen during reference run, but 0 seen during testing run",
"State-update summaries inconsistency: statefulset/default/appian-k8s-service-manager-forums DELETED inconsistency: 1 event(s) seen during reference run, but 0 seen during testing run"
```
I was assuming your test case is supposed to make the controller delete the statefulset (as it is in the reference run). If so, it might to interesting to see why in the test run the statefulset is never deleted.

**Comment by robbie-demuth** [comment]
Hey, @marshtompsxd !

I'm circling back to this after being OOO for a while. I've got all of the results back now, but I didn't apply a mask b/c I didn't want to accidentally mask what may be bugs prematurely. Is there any way to apply a mask post-fact? I'm writing a script akin to `report_bugs.py` that suppresses false positives, but it's just scanning the detected errors. I tried looking at the Python code that applies masks during learning (?) and testing and got a bit lost.

Anyway, I think the biggest source of false positives is termination. My test case creates a custom resource, waits for the corresponding app to start, and deletes it. The custom resource has a finalizer so that the controller can do graceful shutdown. The controller gracefully scales down the stateful sets in an app-specific order, but does not delete them (or any other secondary resource for that matter). Secondary resources are garbage collected by Kubenetes once the custom resource has been deleted b/c of the owner references the controller sets up. My guess is that differences in how long the GC took between the reference run and the testing runs are causing a lot of the false positives. Any idea how to account for that (hopefully w/out re-learning / re-testing)? I'm having trouble determining if there are any real bugs based on the sheer number of what I think are false positives.

Thanks!

**Comment by marshtompsxd** [comment]
Hi @robbie-demuth Thanks for letting me know about your test results.

> Is there any way to apply a mask post-fact?

If you still keep your test raw data, that is, the files in `log/`, you can run
```
python3 sieve.py -p your-controller -c test-plan-folder -b --phase=check
```
And in `sieve_test_results` folder you will have the new test result json updated by your new masks.

> Secondary resources are garbage collected by Kubenetes once the custom resource has been deleted b/c of the owner references the controller sets up. My guess is that differences in how long the GC took between the reference run and the testing runs are causing a lot of the false positives. Any idea how to account for that (hopefully w/out re-learning / re-testing)?

From your description, the difference in whether the GC has deleted the secondary resources is very likely to be the reason of false alarms. If in one run the GC runs a bit faster and deletes all the resources, while in the other run the GC is a bit slow and does not delete anything, Sieve will detect many inconsistencies and report them as alarms (tho they might not be bugs).

This is actually a common problem when running end-to-end tests since one kubectl command might trigger many controller actions in the background (creation/update/deletion) and it is hard to estimate how long all these actions are finished and the cluster becomes stable again. The simple but effective approach we were using is to wait for certain resource getting created/deleted in the test case. For example we have some APIs to wait for certain conditions (terminated, running) of certain resources (pod, statefulset) in the test case like this: https://github.com/sieve-project/sieve/blob/684644d03a91863956fcd283d132beb1c84eb4a6/examples/rabbitmq-operator/test/test.py#L16.

Unfortunately, rerunning the learning/test is necessary if you modify the test case to add more wait-for-xxx, because Sieve will need the new trace (where secondary resources are correctly deleted by GC if there is no bug triggered) generated by the modified test case to detect bugs.

**Comment by lalithsuresh** [comment]
>  The simple but effective approach we were using is to wait for certain resource getting created/deleted in the test case. For example we have some APIs to wait for certain conditions (terminated, running) of certain resources (pod, statefulset) in the test case like this:

@marshtompsxd this is probably a best practice we should mention in the documentation.

**Comment by marshtompsxd** [comment]
Hi @robbie-demuth Please let us know if you encounter more difficulty in using Sieve or any improvement/feature you want to see in Sieve.

**Comment by robbie-demuth** [comment]
Hey, @marshtompsxd. Will do 👍 I'll go ahead and close this for now
